import java.io.FileNotFoundException;
import java.io.FileReader;


public class produceCliquesMatrix {

	
	
	
	
	public static void main(String[] args) throws Exception {
		FileReader f = null;
		Scanner s = null;
		
		if(args.length < 1 || args[0].equals("-h")){
			System.out.println("Usage: java -jar produceCliques.jar cliqueFile\n" +
					"\tcliQueFile is a file generated by tarjan.\n" + 
					"\tWrites file cliqueFile.matrix.dat");
		}
		
		try {
			f = new FileReader(args[0]);
			s = new BufferedReader(new va)
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return;
		}
		int[][] m = new int[100][100];
		int j = 1;
		char c;
		// consume first line JAVAGENT
		// char c = nextChar(f);
		// while(c != '\n'){ c = nextChar(f); }
		
		c = nextChar(f);
		while(c != 'E'){
			while(c!= '}'){
				// Consumes {
				c = nextChar(f);
				String buf = "";
				while(c!= ','){
					buf += c;
					c = nextChar(f);
				}
				int x,y, k = Integer.parseInt(buf);
				
				switch (buf.length()) {
					case 1:
					case 2:
						x = 0;
						y = k;
						break;
					case 3:
					case 4:
						x = k / 100;
						y = k % 100;
					default:
						throw new Exception("Buffer vuoto, c = " + c + ", buffer :" + buf);
				}
				m[x][y] = j * 10;
			}
			j++;
			// consume \n
			c = nextChar(f);
			// read new char
			c = nextChar(f);
		}
		
		System.out.println(m);

	}

}
